version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.maven
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - .:/app
      - maven_cache:/root/.m2

  db:
    image: postgres:16
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  maven_cache:
  postgres_data: